//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableReadyADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableInGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableInGroup()
        {
            this.TableAvailabilityDates = new HashSet<TableAvailabilityDate>();
        }
    
        public int TableID { get; set; }
        public int TableGroupID { get; set; }
        public int MaxTableSeatNumber { get; set; }
        public Nullable<decimal> TablePosX { get; set; }
        public Nullable<decimal> TablePosY { get; set; }
        public string RestaurantArea { get; set; }
        public string RestaurantZone { get; set; }
        public Nullable<int> RestaurantFloor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableAvailabilityDate> TableAvailabilityDates { get; set; }
        public virtual TableGroup TableGroup { get; set; }
        public virtual Table Table { get; set; }
    }
}
