//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableReadyADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table()
        {
            this.TableInGroups = new HashSet<TableInGroup>();
            this.ReservationEntries = new HashSet<ReservationEntry>();
            this.WaitlistEntries = new HashSet<WaitlistEntry>();
        }
    
        public int TableID { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public string TableName { get; set; }
        public int TableMaxNumberSeats { get; set; }
        public string TableImage { get; set; }
        public string TableImageAvailable { get; set; }
        public string TableImageUnavailable { get; set; }
        public string TableImageCheckout { get; set; }
        public string TableImageCleaning { get; set; }
        public string TableType { get; set; }
        public string TableSize { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool TableActive { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableInGroup> TableInGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationEntry> ReservationEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitlistEntry> WaitlistEntries { get; set; }
    }
}
