//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableReadyADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableAvailabilityDate
    {
        public int TableID { get; set; }
        public System.DateTime C_Datetime { get; set; }
        public int TableGroupID { get; set; }
        public string AvailabilityStatus { get; set; }
        public string CheckOutStatus { get; set; }
        public string CleaningStatus { get; set; }
    
        public virtual TableInGroup TableInGroup { get; set; }
    }
}
