//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableReadyADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TableReadyEntities2 : DbContext
    {
        public TableReadyEntities2()
            : base("name=TableReadyEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authentication> Authentications { get; set; }
        public virtual DbSet<AuthenticationMatrix> AuthenticationMatrices { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Layout> Layouts { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<ReservationEntry> ReservationEntries { get; set; }
        public virtual DbSet<RestaurantEmployee> RestaurantEmployees { get; set; }
        public virtual DbSet<RestaurantOwner> RestaurantOwners { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<TableAvailabilityDate> TableAvailabilityDates { get; set; }
        public virtual DbSet<TableGroup> TableGroups { get; set; }
        public virtual DbSet<TableInGroup> TableInGroups { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WaitlistEntry> WaitlistEntries { get; set; }
    }
}
