//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableReadyADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableGroup()
        {
            this.TableInGroups = new HashSet<TableInGroup>();
        }
    
        public int TableGroupID { get; set; }
        public int LayoutID { get; set; }
        public string TableGroupName { get; set; }
        public Nullable<int> TableGroupPriority { get; set; }
        public Nullable<decimal> TableGroupPosX { get; set; }
        public Nullable<decimal> TableGroupPosY { get; set; }
        public string TableGroupImage { get; set; }
        public bool TableGroupActive { get; set; }
    
        public virtual Layout Layout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableInGroup> TableInGroups { get; set; }
    }
}
